### ISSUE TITLE
Can't cd into `/vagrant`

### ISSUE THREAD

**Issue by aslakhellesoy** [bhrrc/modernslaveryregistry.org#51]
The README states:

```
# On the host machine
$ vagrant up
$ vagrant ssh

# On the Vagrant VM
$ cd /vagrant/
```

I've tried this, but once I've ssh'ed into the vagrant box I don't have a `/vagrant` directory.
The current direcotry is `/home/vagrant`, which is empty.

**Comment by aslakhellesoy** [comment]
When I run `vagrant up` I am asked for a password, but I don't know what it is:

```
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 5.2.22
    default: VirtualBox Version: 6.0
==> default: Configuring and enabling network interfaces...
==> default: Exporting NFS shared folders...
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
Password:
```

Could it be that failure to supply this password breaks shared folders?

**Comment by chrisroos** [comment]
That'll be your system password, @aslakhellesoy. And I suspect that will be the problem - I think it needs to update something on your system to enable the shared folder.

**Comment by aslakhellesoy** [comment]
I did supply my host user's OS X password. Any idea what else I need to do?

**Comment by aslakhellesoy** [comment]
Seems relevant: https://github.com/hashicorp/vagrant/issues/10234

**Comment by aslakhellesoy** [comment]
Turns out the trick was to run the command in the MacOS Terminal and *not* in iTerm. Only Terminal pops up this window:

<img width="639" alt="Screenshot 2019-03-18 at 14 02 08" src="https://user-images.githubusercontent.com/1000/54535493-91ad2680-4986-11e9-9995-b9d28fc9c332.png">

It's only after OKing that `vagrant up` completes successfully with a mounted `/vagrant`.

**Comment by chrisroos** [comment]
Aha! Thanks for sticking with it and getting to the bottom of the problem, @aslakhellesoy. What a pain!
