### ISSUE TITLE
Foreman gem not part of the development group

### ISSUE THREAD

**Issue by btoone** [bhrrc/modernslaveryregistry.org#58]
Suggest adding `foreman` gem to the development group. Its not always installed by default and the developer gets an error when attempting to launch the app when its not installed.

**Comment by matthewford** [comment]
Closing this issue, it's recommended not to bundle foreman and it is possible to run the app outside of foreman: https://github.com/ddollar/foreman/wiki/Don't-Bundle-Foreman
